### ISSUE TITLE
Unexpected Scroll Value

### ISSUE THREAD

**Issue by RhinoInani** [spkersten/flutter_coast#11]
Hi,
I keep getting this error from Coast, on the initial release of my website it worked fine but soon after it started degrading (especially the coast animations). Let me know what you think can be causing this error because it is messing up a lot of animations on my website. 

````
======== Exception caught by scheduler library =====================================================
The following TypeErrorImpl was thrown during a scheduler callback:
Unexpected null value.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 518:63  nullCheck
packages/coast/src/crab.dart 143:61                                               <fn>
packages/flutter/src/scheduler/binding.dart 1144:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1090:9                                handleDrawFrame
...
====================================================================================================
````

Below are a few of the usages I have for coast. Please let me know how I can fix this error.

**One Screen:** 
````
              Crab(
                  tag: "text",
                  child: Container(
                    height: size.height * 0.22,
                    width: size.width * 0.24,
                    child: RichText(
                      text: TextSpan(
````

**Another Screen:** 
````
               Crab(
                  tag: "text",
                  child: Center(
                    child: Container(
                      width: size.width * 0.3,
                      height: size.height * 0.1,
                      child: RichText(
````

**Main File:**
````
child: Coast(
          controller: _coastController,
          scrollDirection: Axis.vertical,
          dragStartBehavior: DragStartBehavior.down,
          beaches: [
            Beach(builder: (context) => IntroPage(size: size)),
            Beach(builder: (context) => BiWeeklyReadingsPage(size: size)),
            Beach(builder: (context) => UpcomingEventsPage(size: size)),
            Beach(builder: (context) => ContactUsPage(size: size)),
          ],
          observers: [
            CrabController(),
          ],
        ),
````

Below is a Screen Recording of the bug. As you can see first the animations aren't as smooth as marketed, and second, when scrolling backward there are many bugs. One that is really bothersome is shifting back from "constant events" to "bi-weekly readings". The animation starts from the side of this page and I'm not sure why. Please help.

https://user-images.githubusercontent.com/69125015/132930929-9fc0d569-fb31-4b9e-8ed6-67ad4367493d.mov

Keep up the great work!

Thanks,
Rhino Inani

**Comment by spkersten** [comment]
I'll fix the `Unexpected null value` bug.

The second thing you mention is about the transition of one crab into another. This works the same as for Flutter's hero widget: While transitioning, by default, the size and position of the crab is animated between what it has on the source and target pages and the widget of the target page is used. In your case, that doesn't look good because the crab on the source and target pages have different sizes and different content (text) which doesn't handle that well. What you want is to use the `flightShuttleBuilder` parameter of `Crab` to make a transition animation that works well for text.

I think something like this looks good, but it's up to you to pick what you want:
```dart
Widget textFlightShuttleBuilder(
  BuildContext flightContext,
  Animation<double> animation,
  BeachTransitionDirection direction,
  BuildContext fromCrabContext,
  BuildContext? toCrabContext,
) {
  final curvedAnimation = CurvedAnimation(parent: animation, curve: Curves.easeInOutQuart);
  return Stack(
    clipBehavior: Clip.none,
    children: [
      Positioned(
        top: 0,
        left: 0,
        child: FadeTransition(
          opacity: Tween<double>(begin: 1.0, end: 0.0).animate(curvedAnimation),
          child: (fromCrabContext.widget as Crab).child,
        ),
      ),
      if (toCrabContext != null)
        Positioned(
          top: 0,
          left: 0,
          child: FadeTransition(
            opacity: curvedAnimation,
            child: (toCrabContext.widget as Crab).child,
          ),
        ),
    ],
  );
}
```

https://user-images.githubusercontent.com/4456832/132943834-5b4320cc-5156-4e8c-82e5-d48f71fe95b8.mov

**Comment by RhinoInani** [comment]
Hi,
Reply 1: Sounds great! Doesn't seem to be a huge issue but just wanted to let you know. :)

Reply 2: Thank you so much! That code works perfectly for me! Looks amazing and keep up the great work!

Thanks,
Rhino Inani
